name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.TOKEN }}  #这里是添加的token，不用设置，需要在仓库中添加TOKEN，$代表的是调用刚才添加的环境变量，所以不需要设置
          submodules: 'true'
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: config1 
        run: rm -rf content/.obsidian content/cedict_ts.u8 content/Extras/Templates  && mv content/*.md content/Atlas && find content/ -name "*.md" | xargs -I file  mv -f file content &&  mv content/AboutTheGarden.md content/_index.md 

      - name: config2
        ## run: "ls content/ && grep -lr --null 'title' content/* | xargs -0 sed -i -E -r 's/title: "(.*)/title: \"\\1\"/g'""
        run: ls content/ && grep -lr --null 'title' content/* | xargs -0 sed -i -E -r 's/title: "(.*)/title: \"\\1\"/g'


      - name: config3 
        run: rm -rf content/*.md-E


      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.18
        with:
          index: true
          input: content
          output: assets/indices
          root: .


      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify --debug

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
          cname: www.baidu.com   #修改成你的域名
